# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy custom Nginx configuration file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for Nginx
EXPOSE 80
